version: '2'
services:
  mysql:
    image: mysql:5.7.16
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --max_connections=1000
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=mitorizu_renew
      - MYSQL_ROOT_PASSWORD=root
